# Generated by Django 5.2.5 on 2025-09-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose1_date', models.DateField()),
                ('dose2_date', models.DateField(blank=True, null=True)),
                ('dose1_status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='BOOKED', max_length=20)),
                ('dose2_status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('doses_required', models.PositiveIntegerField(default=2)),
                ('dose_interval_days', models.PositiveIntegerField()),
            ],
        ),
    ]
